server:
    port: 9000
    content-path: #//
    #设置服务器session过期时间
    session:
      timeout: 86400

logging:
    level:
#    pattern:
#      file:

spring:
    http:
        multipart:
          maxFileSize: 100Mb
          maxRequestSize: 1000Mb
    #百度插件需要的配置
    resources:
      static-locations:  classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
      #static-locations:  classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    mvc:
      #百度插件需要的配置
      static-path-pattern: /**
      view:
        prefix: /templates/
        suffix: .ftl

    freemarker:
      cache: false
      expose-spring-macro-helpers: true
      request-context-attribute: context

    datasource:
      url: jdbc:mysql://127.0.0.1:3306/qxbbs?useUnicode=true&characterEncoding=utf8
      username: root
      password:
#      password: 125011
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

mybatis:
  mapperLocations: com.bbs.mapper
  typeAliasesPackage: com.bbs.model

#百度插件需要的配置
web:
  upload-path: C:/
  #upload-path: http://localhost:9000/qxpolicebbs/



